ci-look: 
    badges:
        logo.height: 60
        logo.width: 60
        logo.type: PNG
    
    version:
        id: ${app.build.version}
        codeName: ${app.build.codeName}
        build: ${app.build.timestamp}
        
spring:   
    profiles:
        active: h2console,swagger
       
    datasource:
        url: jdbc:h2:~\h2;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password: i'sE2rtPiUKtT
        driver-class-name: org.h2.Driver
       
    jpa:
        show-sql: false
        
    main:
        banner_mode: "off"