---
## PANORAMA CONFIG
panorama: 
    badges:
        logo.height: 20
        logo.width: 73
        logo.type: PNG
    
    version:
        id: ${app.build.version}
        codeName: ${app.build.codeName}
        build: ${app.build.timestamp}
        
    ## TODO : use instead of spring profiles    
    options:
        demo-data: true
        h2console: true
        swagger: true
    
    ## Cache type between "compressed", "default", "none"
    badges-cache:
        type: "compressed"
        
    ## IDEAS FOR CLI
    cli:
        cat-enabled: true
        
spring:   
    profiles:
        active: h2console,swagger,demo
       
    datasource:
        url: jdbc:h2:~\h2;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password: i'sE2rtPiUKtT
        driver-class-name: org.h2.Driver
       
    jpa:
        show-sql: false
